version: "3.7"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_container:/data/db
  # app:
  #   container_name: test
  #   build: .
  #   ports:
  #     - 3000:3000

volumes:
  mongodb_container:
